# Intro to Python and Jupyter-Notebooks
<img src="http://www.python.org/static/community_logos/python-logo-generic.svg" align="left" width="300" >

<p style="width:35%;float:right;padding-left:50px">
<img src="http://certik.github.io/talk-scipy-india2013/talk/images/python_ecosystem.png">
<img src="http://luispedro.org/files/talks/2013/EuBIAS/figures/sciwheel.png">
</p>

## Why Python?

* Widely used in all areas, picking up lots of momentum in many sciences
* Simple, concise, and easy-to-read syntax
* Free and Open Source, large scientific community
* Potentially high impact and large user base
* General purpose programming language
* Cross-platform: from RaspberryPi to large supercomputers
* No need to compile, interactive shell available
* Easy to interact with existing C and Fortran code
* Vast scientific ecosystem; taking advantage of developments in other sciences

## External Resources
If you have any question regarding some specific Python functionality you can consult the official [Python documenation](http://docs.python.org/3/).

Furthermore a large number of Python tutorials, introduction, and books are available online. Here are some examples for those interested in learning more.

* [Python Numerical Methods](https://pythonnumericalmethods.berkeley.edu/notebooks/Index.html) **This lab's exercises are mostly straight from this "digital-textbook," although some modifications have been made.**
* [Learn Python The Hard Way](http://learnpythonthehardway.org/book/)
* [Dive Into Python](http://www.diveintopython.net/)
* [The Official Python Tutorial](http://docs.python.org/3/tutorial/index.html)
* [Think Python Book](http://www.greenteapress.com/thinkpython/thinkpython.html)

Some people might be used to Matlab - this helps:

* [NumPy for Matlab Users Introdution](https://numpy.org/doc/stable/user/numpy-for-matlab-users.html)
* [NumPy for Matlab Users Cheatsheet](http://mathesaurus.sourceforge.net/matlab-numpy.html)


Additionally there is an abundance of resources introducing and teaching parts of the scientific Python ecosystem.

* [Awesome Python](https://github.com/vinta/awesome-python) Need we say more?
* [NumPy Tutorials](https://numpy.org/doc/stable/user/tutorials_index.html)
* [Probabilistic Programming and Bayesian Methods for Hackers](http://camdavidsonpilon.github.io/Probabilistic-Programming-and-Bayesian-Methods-for-Hackers/): Great ebook introducing Bayesian methods from an understanding-first point of view with the examples done in Python.
* [Python Scientific Lecture Notes](http://scipy-lectures.github.io/): Introduces the basics of scientific Python with lots of examples.
* [Notebook introducing SymPy](http://nbviewer.ipython.org/github/ipython/ipython/blob/master/examples/notebooks/SymPy%20Examples.ipynb): Notebook showing off the symbolic mathematics packages SymPy.
* [Python for Signal Processing](http://python-for-signal-processing.blogspot.de/): Free blog which is the basis of a proper book written on the subject.
* [Another NumPy Tutorial](http://www.loria.fr/~rougier/teaching/numpy/numpy.html)
* [Matplotlib Tutorial](http://www.loria.fr/~rougier/teaching/matplotlib/matplotlib.html)


## Exercise 1: Python Basics

For this Exercise, you need to commplete all the following problems. Please comment your code when neccessary. Most of these problems were taken straight from  [Python Numerical Methods](https://pythonnumericalmethods.berkeley.edu/notebooks/chapter01.06-Summary-and-Problems.html#problems), but there have been modifications. Please read Chapter 1.

#### For problems 1-3, please use a stand-alone cell for each problem.
1. Print "I love Python" (including the quotes).<br><br>

1. *import antigravity*<br><br>

1. *import true*

#### For problems 4-7, please lump them into just one cell, but use comments to indecate each problem
4. Compute the surface area and volume of a cylinder with radius 5 and height 3 (Use numpy's variable for Pi).<br><br>

1. Compute the slope between the points $(3,4)$ and $(5,9)$. Recall that the slope between points $(x_1,y_1)$ and $(x_2, y_2)$ is $\frac{y_2 - y_1}{x_2 - x_1}$. Be sure you have the correct order of operations.<br><br>

1. Compute the distance between the points $(3,4)$ and $(5,9)$. Recall that the distance between points in two dimensions is $\sqrt{(x_2 - x_1)^2 + (y_2 - y_1)^2}$. Be sure you have the correct order of operations, and do NOT use a function when computing the square-root. (Hint: when taking the square-root, think about how you can write the square-root as a power).<br><br>

1. Use Python's *factorial* function (or Numpy's if you know it) to compute $6!$

#### For problem 8, please use a stand-alone cell
8. A very powerful approximation for $\pi$ was developed by a brilliant mathematician named Srinivasa Ramanujan. The approximation is the following:<br>
$\frac{1}{\pi} \approx \frac{2\sqrt{2}}{9801} \sum_{k=0}^{N} \frac{(4k)!(1103 + 26390k)}{(k!)^4 396^{4k}}$.<br>
Use Ramanujan's formula for $N = 0$ and $N = 1$ to approximate $\pi$. Be sure to use format long. Compare your approximation with Numpy's stored value for *pi*. Hint: $0! = 1$ by definition.

#### For problems 9-11, please lump them into just one cell, but use comments to indecate each problem
9. The hyperbolic $sin$ or $sinh$ is defined in terms of exponentials as $sinh(x) = \frac{\exp(x) - \exp(-x)}{2}$.<br>
Compute $sinh$ for $x = 2$ using exponentials. Verify that the result is indeed the hyperbolic $sin$ using Python's function *sinh* in the math module. <br><br>

1. Verify that $\sin^2(x) + \cos^2(x) = 1$ for $x = \pi, \frac{\pi}{2}, \frac{\pi}{4}, \frac{\pi}{6}$.<br><br>

1. Compute the $\sin87$&deg;<br><br>

#### For problems 12_14, please lump them into just one cell, but use comments to indecate each problem
12. If $P$ is a logical expression, the law of noncontradiction states that $P\ AND\ (NOT\ P)$ is always false. Verify this for $P$ true and $P$ false.<br><br>

1. Let P and Q be logical expressions. De Morgan's rule states that $NOT\ (P\ OR\ Q)\ =\ (NOT\ P)\ AND\
(NOT\ Q)$ and $NOT\ (P\ AND\ Q)\ =\ (NOT\ P)\ OR\ (NOT\ Q)$. Generate the truth tables for each statement to show that De Morgan's rule is always true.<br><br>

1. The logical operator XOR has the following truth table:<br>
Construct an equivalent logical expression for XOR using only AND, OR, and NOT that has the same truth table (see the following figure)  ![XOR](https://pythonnumericalmethods.berkeley.edu/_images/01.06.01-truth_table.png)<br><br>

#### For problem 15, please use a stand-alone cell 
1. Do the following calculation.<br>
$e^{2}\sin{\pi/6} + log_e(3)\cos{\pi/9}-5^3$

**Start adding cells for Exercise 1 below here.  Edit this markdown cell with a '##" size heading stating, "My solutions to Exercise 1."**

## My solutions to Exercise 1 ##

In [2]:
print('\'I love Python\'')

'I love Python'


In [4]:
import antigravity

In [18]:
import this

The Zen of Python, by Tim Peters

Beautiful is better than ugly.
Explicit is better than implicit.
Simple is better than complex.
Complex is better than complicated.
Flat is better than nested.
Sparse is better than dense.
Readability counts.
Special cases aren't special enough to break the rules.
Although practicality beats purity.
Errors should never pass silently.
Unless explicitly silenced.
In the face of ambiguity, refuse the temptation to guess.
There should be one-- and preferably only one --obvious way to do it.
Although that way may not be obvious at first unless you're Dutch.
Now is better than never.
Although never is often better than *right* now.
If the implementation is hard to explain, it's a bad idea.
If the implementation is easy to explain, it may be a good idea.
Namespaces are one honking great idea -- let's do more of those!


In [11]:
import numpy as np
#compute cylinder's surface area and volume with radius 5 and height 3
print('Cylinder\'s surface area is', 2*np.pi*5*3+np.pi*5*5*2)
print('Cylinder\'s volume is', np.pi*5*5*3)

#the slope between two points
x1 = [3,4]
x2 = [5,9]
print('The slope is', (x2[1]-x1[1])/(x2[0]-x1[0]))

#the distance between two points
print('The distance is', ((x1[0]-x2[0])**2+(x1[1]-x2[1])**2)**0.5)

#factorial of 6
print('6! is', np.math.factorial(6))

Cylinder's surface area is 251.32741228718345
Cylinder's volume is 235.61944901923448
The slope is 2.5
The distance is 5.385164807134504
6! is 720


In [17]:
# Ramanujan's method
def ramanujan(k):
    return 2*np.sqrt(2)/9801*np.math.factorial(4*k)*(1103+26390*k)/(np.math.factorial(k)**4*396**(4*k))
#N=0
print('N=0, result is ', 1/ramanujan(0), 'while pi is ', np.pi)

#N=1
print('N=1, result is ', 1/(ramanujan(0)+ramanujan(1)), 'while pi is ', np.pi)

N=0, result is  3.1415927300133055 while pi is  3.141592653589793
N=1, result is  3.1415926535897936 while pi is  3.141592653589793


In [26]:
# sinh function
import math
expo = (np.exp(2)-np.exp(-2))/2
print('exponential result is ',expo)
print('math module result is ', math.sinh(2))

#verify sin(x)^2+cos(x)^2=1 for pi/2, pi/4, pi/6
print('sin(pi/2): ', np.sin(np.pi/2), 'cos(pi/2):', np.cos(np.pi/2),'\n', np.sin(np.pi/2)**2,'+', np.cos(np.pi/2)**2,'=',np.sin(np.pi/2)**2+np.cos(np.pi/2)**2)
print('sin(pi/4): ', np.sin(np.pi/4), 'cos(pi/4):', np.cos(np.pi/4),'\n', np.sin(np.pi/4)**2,'+', np.cos(np.pi/4)**2,'=',np.sin(np.pi/4)**2+np.cos(np.pi/4)**2)
print('sin(pi/6): ', np.sin(np.pi/6), 'cos(pi/6):', np.cos(np.pi/6),'\n', np.sin(np.pi/6)**2,'+', np.cos(np.pi/6)**2,'=',np.sin(np.pi/6)**2+np.cos(np.pi/6)**2)

#sin 87
print('sin 87 is ', np.sin(87/180*np.pi))

exponential result is  3.626860407847019
math module result is  3.6268604078470186
sin(pi/2):  1.0 cos(pi/2): 6.123233995736766e-17 
 1.0 + 3.749399456654644e-33 = 1.0
sin(pi/4):  0.7071067811865475 cos(pi/4): 0.7071067811865476 
 0.4999999999999999 + 0.5000000000000001 = 1.0
sin(pi/6):  0.49999999999999994 cos(pi/6): 0.8660254037844387 
 0.24999999999999994 + 0.7500000000000001 = 1.0
sin 87 is  0.9986295347545738


In [16]:
#logic
P = True
print('When P is True: P AND NOT P', P and not P)
P = False
print('When P is False: P AND NOT P', P and not P)

#de morgan
print('P\tQ\tNOT(P OR Q)\t(NOT P) AND (NOT Q)\tNOT (P AND Q)\tNOT P OR NOT Q')
P = True
Q = True
print(P,'\t', Q, '\t', not (P or Q), '\t', (not P) and (not Q), '\t', not(P and Q), '\t', (not P) or (not Q))
P = True
Q = False
print(P,'\t', Q, '\t', not (P or Q), '\t', (not P) and (not Q), '\t', not(P and Q), '\t', (not P) or (not Q))
P = False
Q = True
print(P,'\t', Q, '\t', not (P or Q), '\t', (not P) and (not Q), '\t', not(P and Q), '\t', (not P) or (not Q))
P = False
Q = False
print(P,'\t', Q, '\t', not (P or Q), '\t', (not P) and (not Q), '\t', not(P and Q), '\t', (not P) or (not Q))

#xor
P = True
Q = True
print('P is', P, 'Q is', Q, 'XOR is', (not P and Q) or (not Q and P))
P = True
Q = False
print('P is', P, 'Q is', Q, 'XOR is', ((not P) and Q) or ((not Q) and P))
P = False
Q = True
print('P is', P, 'Q is', Q, 'XOR is', (not P and Q) or (not Q and P))
P = False
Q = False
print('P is', P, 'Q is', Q, 'XOR is', (not P and Q) or (not Q and P))

When P is True: P AND NOT P False
When P is False: P AND NOT P False
P	Q	NOT(P OR Q)	(NOT P) AND (NOT Q)	NOT (P AND Q)	NOT P OR NOT Q
True 	 True 	 False 	 False 	 False 	 False
True 	 False 	 False 	 False 	 True 	 True
False 	 True 	 False 	 False 	 True 	 True
False 	 False 	 True 	 True 	 True 	 True
P is True Q is True XOR is False
P is True Q is False XOR is True
P is False Q is True XOR is True
P is False Q is False XOR is False


In [19]:
import numpy as np
print(np.e**2*np.sin(np.pi/6)+np.log(3)*np.cos(np.pi/9)-5**3)

-120.27311408976854


## Exercise 2: Variables and Basic Data Structures

For this Exercise, you need to commplete all the following problems. Please comment your code when neccessary. Most of these problems were taken straight from  [Python Numerical Methods](https://pythonnumericalmethods.berkeley.edu/notebooks/chapter02.08-Summary-and-Problems.html#problems), but there have been modifications. Please read Chapter 2.

#### For problems 1 and 2, please use a stand-alone cell for each problem
1. Let x = 10 and y = 3. Write in a stand-alone cell the following lines of code for each of the following assignments.

```python
u = x + y
v = x*y
w = x/y
z = sin(x)
r = 8*sin(x) 
s = 5*sin(xy)
p = x**y
```
2. In a stand-alone cell, show all the variables in the Jupyter notebook after you finish problem 1.<br><br>

#### For problems 3-10, please lump them into just one cell, but use comments to indecate each problem
3. Assign string '123' to the variable S. Convert the string into a float type and assign the output to the variable N. Verify that S is a string and N is a float using the *type* function. <br><br>

1. Assign the string 'HELLO' to the variable s1 and the string 'hello' to the variable s2. Use the *==* operator to show that they are not equal. Use the *==* operator to show that s1 and s2 are equal if the *lower* method is used on s1. Use the **==** operator to show that s1 and s2 are equal if *upper* method is used on s2.<br><br>

1. Show all the variables in the Jupyter notebook after you finish problem 3.<br><br>

1. Assign string '123' to the variable S. Convert the string into a float type and assign the output to the variable N. Verify that S is a string and N is a float using the *type* function. <br><br>

1. Assign the string 'HELLO' to the variable s1 and the string 'hello' to the variable s2. Use the *==* operator to show that they are not equal. Use the *==* operator to show that s1 and s2 are equal if the *lower* method is used on s1. Use the **==** operator to show that s1 and s2 are equal if *upper* method is used on s2. <br><br>

1. Use the *print* function to generate the following string: "The word 'flabbergasted' has \<number of\> letters." <br><br>

1. Check if 'Python' is in 'Python is great!' and print the result. <br><br>

1. Get and print the last word 'great' from 'Python is great!'<br><br>

#### For problems 11-16, please lump them into just one cell, but use comments to indecate each problem
11. Assign list [1, 8, 9, 15] to a variable *list_a* and insert 2 at index 1 using the *insert* method. Append 4 to the *list_a* using the *append* method. <br><br>

1. Sort the *list_a* in problem 10 in ascending order and print the result. <br><br>

1. Turn 'Python is great!' to a list. <br><br>

1. Create a tuple with with the following two elements, 'One' and 1, and assign it to tuple_a<br><br>

1. Get and print the 2nd element in the tuple_a in problem 13. <br><br>

1. Get and print the unique element from (2, 3, 2, 3, 1, 2, 5). <br><br>

#### For problems 17-19, please lump them into just one cell, but use comments to indecate each problem
17. Assign (2, 3, 2) to set_a, and (1, 2, 3) to set_b. Get the following:
    * union of set_a and set_b
    * intersection of set_a and set_b
    * difference of set_a to set_b using *difference* method<br><br>

1. Create a dictionary that has the keys 'A', 'B', 'C' with values 'a', 'b', 'c' individually. Print all the keys in the dictionary. <br><br>

1. Check if key 'B' is in the dictionary defined in problem 17. <br><br>

#### For problems 20-24, please lump them into just one cell, but use comments to indecate each problem
20. Generate an array with size 100 evenly spaced between -10 to 10 using *linspace* function in Numpy.<br><br>

1. Let array_a be an array [-1, 0, 1, 2, 0, 3]. Write a command that will return an array consisting of all the elements of array_a that are larger than zero. Hint: Use logical expression as the index of the array.<br><br>

1. Create an array $y = \begin{pmatrix} 
3 & 5 & 3 \\
2 & 2 & 5 \\
3 & 8 & 9 \\
\end{pmatrix}$ and calculate the transpose of the array. <br><br>

1. Create a zero array with size (2, 4). <br><br>

1. Change the 2nd column in the above array to 1.  <br><br>

#### For problem 25, please use a stand-alone cell 
25. Write a cell magic to clear all the variables in the Jupyter notebook

**Start adding cells for Exercise 2 below here.  Edit this markdown cell with a '##" size heading stating, "My solutions to Exercise 2."**

## My solution to Exercise 2 ##

In [24]:
import numpy as np
x = 10
y = 3
u = x + y
v = x*y
w = x/y
z = np.sin(x)
r = 8*np.sin(x) 
s = 5*np.sin(x*y)
p = x**y

In [25]:
print(x,y,u,v,w,z,r,s,p)

10 3 13 30 3.3333333333333335 -0.5440211108893698 -4.352168887114958 -4.940158120464309 1000


In [30]:
# problem 3
S = '123'
N = float(S)
print(type(S), type(N))
# problem 4
s1 = 'HELLO'
s2 = 'hello'
print(s1==s2)
print(s1.lower()==s2)
print(s1 == s2.upper())
# problem 5
print(S,N,s1,s2)

#problem 8
print('\"The word \'flabbergasted\' has %d letters.\"'%len('flabbergasted'))

#problem 9
word = 'Python'
if word in 'Python is great!':
    print('True')
    
#problem 10
sentence = 'Python is great!'
print(sentence[-6:-1])

<class 'str'> <class 'float'>
False
True
True
123 123.0 HELLO hello
"The word 'flabbergasted' has 13 letters."
True
great


In [36]:
#problem 11
list_a = [1, 8, 9, 15]
list_a.insert(1, 2)
list_a.append(4)

#problem 12
list_a.sort()
print(list_a)

#problem 13
sentence = list('Python is great!')

#problem 14
tuple_a = ('One', 1)

#problem 15
print(tuple_a[1])

#problem 16
list_b = [2,3,2,3,1,2,5]
print(set(list_b))

[1, 2, 4, 8, 9, 15]
1
{1, 2, 3, 5}


In [44]:
#problem 17
set_a = {2,3,2}
set_b = {1,2,3}
print(set_a.union(set_b))
print(set_a.intersection(set_b))
print(set_a.difference(set_b))

#problem 18
d = {"A":'a', 'B':'b', 'C':'c'}
print(d.keys())

#problem 19
if 'B' in d:
    print(True)

{1, 2, 3}
{2, 3}
set()
dict_keys(['A', 'B', 'C'])
True


In [50]:
#problem 20
import numpy as np
array = np.linspace(-10, 10, 100)

#problem 21
array_a = np.array([-1,0,1,2,0,3])
print(array_a[array_a>0])

#problem 22
y = np.array([[3,5,3], [2,2,5], [3,8,9]])
print(y.T)

#problem 23
a = np.zeros([2,4])
print(a)

#problem 24
a[:,1]=1
print(a)

[1 2 3]
[[3 2 3]
 [5 2 8]
 [3 5 9]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 1. 0. 0.]
 [0. 1. 0. 0.]]


In [52]:
#problem 25
%reset

Once deleted, variables cannot be recovered. Proceed (y/[n])? y


## Exercise 3: Functions

For this Exercise, you need to commplete all the following problems. Please comment your code when neccessary. Most of these problems were taken straight from  [Python Numerical Methods](https://pythonnumericalmethods.berkeley.edu/notebooks/chapter03.06-Summary-and-Problems.html#problems), but there have been modifications. Please read Chapter 3.


#### For all of the problems, please use a stand-alone cell for each problem
1. Recall that the hyperbolic sine, denoted by $\sinh$, is $\frac{\exp{(x)} - \exp{(-x)}}{2}$. Write a function $my\_sinh(x)$, where the output $y$ is the hyperbolic sine computed on $x$. Assume that _x_ is a 1 by 1 float.

 Test Cases:

 ```python
 In: my_sinh(0)
 Out: 0
    
 In: my_sinh(1)
 Out: 1.1752
    
 In: my_sinh(2)
 Out: 3.6269
 ```
 
1. Write a function $my\_checker\_board(n)$, where the output $m$ is an $n\times n$ array with the following form:

    $$
    m =\begin{array}{ccccc}
    1 & 0 & 1 & 0 & 1\\
    0 & 1 & 0 & 1 & 0\\
    1 & 0 & 1 & 0 & 1\\
    0 & 1 & 0 & 1 & 0\\
    1 & 0 & 1 & 0 & 1
    \end{array}
    $$

 Note that the upper-left element should always be 1. Assume that _n_ is a strictly positive integer. 
 
 Test Cases:
 
 ```python
 In: my_checker_board(1)
 Out: 1
    
 In: my_checker_board(2)
 Out: array([[1, 0],
             [0, 1]])
    
 In: y = my_sinh(3)
 Out: array([[1, 0, 1],
             [0, 1, 0], 
             [1, 0, 1]])
    
 In: y = my_sinh(5)
 Out: array([[1, 0, 1, 0, 1],
             [0, 1, 0, 1, 0], 
             [1, 0, 1, 0, 1], 
             [0, 1, 0, 1, 0], 
             [1, 0, 1, 0, 1]])
 ```
 
1. Write a function $my\_triangle(b,h)$ where the output is the area of a triangle with base, _b_, and height, _h_. Recall that the area of a triangle is one-half the base times the height. Assume that _b_ and _h_ are just 1 by 1 float numbers.

 Test Cases:
 
 ```python
 In: my_triangle(1, 1)
 Out: 0.5
 
 In: my_triangle(2, 1)
 Out: 1
    
 In: my_triangle(12, 5)
 Out: 30
 ```
 
1. Write a function $my\_split\_matrix(m)$, where $m$ is an array, the output is a list *[m1, m2]* where *m1* is the left half of *m*, and *m2* is the right half of *m*. In the case where there is an odd number of columns, the middle column should go to *m1*. Assume that *m* has at least two columns. **Note: Even if you know how to use "if" statements, do NOT use them for this problem.**

 Test Cases:
 
```python
 In: m = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  
 In: m1, m2 = my_split_matrix(m)  
 Out: m1 = array([[1, 2],
                   [4, 5],
                   [7, 8]])  
 Out: m2 = array([3, 6, 9])
   
  
 In: m = np.ones((5, 5))
 In: m1, m2 = my_split_matrix(m) 
 Out: m1 = array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])
 Out: m2 =  array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])
   
 ```
 
5. Write a function $my\_cylinder(r,h)$, where *r* and *h* are the radius and height of a cylinder, respectively, and the output is a list *[s, v]* where *s* and *v* are the surface area and volume of the same cylinder, respectively. Recall that the surface area of a cylinder is $2\pi r^2 + 2\pi rh$, and the volume is $\pi r^2h$. Assume that *r* and *h* are 1 by 1 float.

 Test Cases:
 
 ```python
 In: my_cylinder(1,5)
 Out: [37.6991, 15.7080]
 
 In: my_cylinder(2,4)
 Out: [62.8319, 37.6991]
 ```
 
1. Write a function $my\_n\_odds(a)$, where *a* is a one-dimensional array of floats and the output is the number of odd numbers in *a*.

 Test Cases:

 ```python
 In: my_n_odds(np.arange(100))
 Out: 50
 
 In: my_n_odds(np.arange(2, 100, 2))
 Out: 0
 ```
 
1. Write a lambda function that takes in *x* and *y*, and output the value of *x - y*. 
 Test Cases:
 ```python
 In: x = 8.5
 In: y = 13
 In: your_lambda_func(x,y)
 Out: -4.5
 
 In: x = 4.9
 In: y = 4.845
 In: your_lambda_func(x,y)
 Out: 0.055
 ```
 **Did you get the correct answer for the 2nd Test Case ([Hint](https://static.wikia.nocookie.net/star-wars-memes/images/c/c3/0F8D75BC-6506-4846-8C68-1EE9687EFC03.jpeg/))?**<br><br>
 
8. Let *r1* and *r2* be the radius of circles with the same center and let *r2>r1*. Write a function *my\_donut\_area(r1, r2)*, where the output is the area outside of the circle with radius *r1* and inside the circle with radius *r2*. Make sure that the function is vectorized. Assume that *r1* and *r2* are one-dimensional array of the same size. 

 Test Cases:
 
 ```python
 In: my_donut_area(np.arange(1, 4), np.arange(2, 7, 2))
 Out: array([9.4248, 37.6991, 84.8230])
 ```
 
1. Write a function $my\_within\_tolerance(A, a, tol)$, where the output is an array or list of the indices in *A* such that  $|A-a| < \text{tol}$. Assume that *A* is a one-dimensional float list or array and that *a* and *tol* are 1 by 1 floats. 

 Test Cases:
 
 ```python
 In: my_within_tolerance([0, 1, 2, 3], 1.5, 0.75)
 Out: [1, 2]
    
 In: my_within_tolerance(np.arange(0, 1.01, 0.01), 0.5, 0.03)
 Out: [47, 48, 49, 50, 51, 52]
 ```
 
1. Write a function $bounding\_array(A, top, bottom)$, where the output is equal to the array *A* wherever *bottom < A < top*, the output is equal to *bottom* wherever *A <= bottom*, and the output is equal to *top* wherever *A >= top*. Assume that *A* is one-dimensional float array and that *top* and *bottom* are 1 by 1 floats. 

 Test Cases:
 
 ```python
 In: bounding_array(np.arange(-5, 6, 1), 3, -3)
 Out: [-3, -3, -3, -2, -1, 0, 1, 2, 3, 3, 3]
 ```

**Start adding cells for Exercise 3 below here.  Edit this markdown cell with a '##" size heading stating, "My solutions to Exercise 3."**

## My solutions to Exercise 3 ##

In [54]:
import numpy as np
def my_sinh(x):
    return (np.exp(x)-np.exp(-x))/2

#test
print(my_sinh(0))
print(my_sinh(1))
print(my_sinh(2))

0.0
1.1752011936438014
3.626860407847019


In [58]:
def my_check_board(n):
    board = np.zeros([n,n])
    for i in range(0,n):
        for j in range(0,n):
            if (i%2==0)&(j%2==0) :
                board[i,j]=1
            if (i%2==1)&(j%2==1):
                board[i,j]=1
    return board
print(my_check_board(1))
print(my_check_board(2))
print(my_check_board(3))
print(my_check_board(5))

[[1.]]
[[1. 0.]
 [0. 1.]]
[[1. 0. 1.]
 [0. 1. 0.]
 [1. 0. 1.]]
[[1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1.]]


In [60]:
def my_triangle(b, h):
    return b*h/2

print(my_triangle(1,1))
print(my_triangle(2,1))
print(my_triangle(12,5))

0.5
1.0
30.0


In [75]:
def my_split_matrix(m):
    return m[:,:int(m.shape[0]/2)+1], m[:, int(m.shape[0]/2)+1:]
m = np.array([[1,2,3], [4,5,6], [7,8,9]])
m1, m2 = my_split_matrix(np.ones([5,5]))
print(m1, m2)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [76]:
def my_cylinder(r, h):
    return np.pi*2*r**2+2*np.pi*r*h, np.pi*h*r**2

my_cylinder(1,5)

(37.69911184307752, 15.707963267948966)

In [78]:
def my_n_odds(a):
    counter = 0
    for i in a:
        if i%2 == 1:
            counter+=1
    return counter
my_n_odds(np.arange(2,100,2))

0

In [82]:
z = lambda x,y:x-y
x = 8.5
y = 13
z(x,y)
x=4.9
y=4.845
z(x,y)

0.055000000000000604

In [83]:
def my_donut_area(r1, r2):
    return np.pi*(r2**2-r1**2)
my_donut_area(np.arange(1,4), np.arange(2,7,2))

array([ 9.42477796, 37.69911184, 84.82300165])

In [89]:
def my_within_tolerance(A,b,tol):
    A = np.array(A)-b
    return np.where(np.abs(A)<tol)
my_within_tolerance(np.arange(0, 1.01, 0.01), 0.5, 0.03)

(array([47, 48, 49, 50, 51, 52]),)

In [90]:
def bounding_array(A, top, bottom):
    A[A<bottom] = bottom
    A[A>top] = top
    return A
bounding_array(np.arange(-5, 6, 1), 3, -3)

array([-3, -3, -3, -2, -1,  0,  1,  2,  3,  3,  3])

## Exercise 4: Branching Statements

For this Exercise, you need to commplete all the following problems. Please comment your code when neccessary. Most of these problems were taken straight from  [Python Numerical Methods](https://pythonnumericalmethods.berkeley.edu/notebooks/chapter04.03-Summary-and-Problems.html#problems), but there have been modifications. Please read Chapter 4.


#### For all of the problems, please use the cells provided for each problem.

### 1.
Write a function `my_tip_calc(bill, party)`, where `bill` is the total cost of a meal and `party` is the number of people in the group. The tip should be calculated as 15% for a party strictly less than six people, 18% for a party strictly less than eight, 20% for a party less than 11, and 25% for a party 11 or more. A couple of test cases are given below. 

In [91]:
def my_tip_calc(bill, party):
    # write your function code here
    if party < 6:
        tips = bill * 0.15
    elif (party > 6)&(party < 8):
        tips = bill * 0.18
    elif (party > 8)&(party < 11):
        tips = bill * 0.2
    elif (party >= 11):
        tips = bill * 0.25
    return tips

In [92]:
# t = 16.3935
t = my_tip_calc(109.29,3) 
print(t)

16.3935


In [93]:
# t = 19.6722
t = my_tip_calc(109.29,7) 
print(t)

19.6722


In [94]:
# t = 21.8580
t = my_tip_calc(109.29,9)
print(t)

21.858000000000004


In [95]:
# t = 27.3225
t = my_tip_calc(109.29,12)
print(t)

27.3225


### 2.
Write a function `my_mult_operation(a,b,operation)`. The input argument, `operation`, is a string that is either `'plus'`, `'minus'`, `'mult'`, `'div'`, or `'pow'`, and the function should compute: $a+b$, $a-b$, $a∗b$, $a/b$, and $a^b$ for the respective values for `operation`. A couple of test cases are given below. 

In [96]:
def my_mult_operation(a,b,operation):
    # write your function code here
    if operation == 'plus':
        out = a + b
    elif operation == 'minus':
        out = a - b
    elif operation == 'mult':
        out = a * b
    elif operation == 'div':
        out = a / b
    elif operation == 'pow':
        out = a**b
    return out

In [97]:
x = np.array([1,2,3,4])
y = np.array([2,3,4,5])

In [98]:
# Output: [3,5,7,9]
my_mult_operation(x,y,'plus')

array([3, 5, 7, 9])

In [99]:
# Output: [-1,-1,-1,-1]
my_mult_operation(x,y,'minus')

array([-1, -1, -1, -1])

In [100]:
# Output: [2,6,12,20]
my_mult_operation(x,y,'mult')

array([ 2,  6, 12, 20])

In [101]:
# Output: [0.5,0.66666667,0.75,0.8]
my_mult_operation(x,y,'div')

array([0.5       , 0.66666667, 0.75      , 0.8       ])

In [102]:
# Output: [1,8,81,1024]
my_mult_operation(x,y,'pow')

array([   1,    8,   81, 1024])

### 3. 
Consider a bounding-box with vertices at $(-1,-1)$, $(-1,1)$, $(1,1), and (1,-1)$. Write a function *my_inside_bbox(x,y)* where the output is the string 'outside' if the point $(x,y)$ is outside of the bouding-box, 'border' if the point is exactly on the border, and 'inside' if the point is on the inside of the bouding-box.

In [107]:
def my_inside_bbox(x,y):
    # write your function code here
    if (abs(x)<1) & (abs(y)<1):
        position = 'inside'
    elif (abs(x)==1) | (abs(y)==1):
        position = 'border'
    else:
        position = 'outside'
    return position

In [108]:
# Output: 'border'
my_inside_bbox(1,0.5)

'border'

In [109]:
# Output: 'inside'
my_inside_bbox(0.25,-0.25)

'inside'

In [110]:
# Output: 'outside'
my_inside_bbox(5,5)

'outside'

### 4.
Write a function *my_make_size10(x)*, where *x* is an array and output is the first 10 elements of *x* if *x* has more than 10 elements, and output is the array *x* padded with enough zeros to make it length 10 if *x* has less than 10 elements.

In [125]:
import numpy as np

def my_make_size10(x):
    # write your function code here
    if len(x)>10:
        size10 = x[:10]
    else:
        l = 10 - len(x)
        size10 = np.hstack([x, np.zeros(l)])
    return size10

In [126]:
# Output: [1,2,0,0,0,0,0,0,0,0]
my_make_size10(np.arange(1,3))

array([1., 2., 0., 0., 0., 0., 0., 0., 0., 0.])

In [127]:
# Output: [1,2,3,4,5,6,7,8,9,10]
my_make_size10(np.arange(1,16))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [128]:
# Output: [3,6,13,4,0,0,0,0,0,0]
my_make_size10(np.array([3,6,13,4,0]))

array([ 3.,  6., 13.,  4.,  0.,  0.,  0.,  0.,  0.,  0.])

### 5.
Most engineering systems have redundancy. That is, an engineering system has more than is required to accomplish its purpose. Consider a nuclear reactor whose temperature is monitored by three sensors. An alarm should go off if any two of the sensor readings disagree. Write a function *my_nuke_alarm(s1,s2,s3)* where *s1*, *s2*, and *s3* are the temperature readings for sensor 1, sensor 2, and sensor 3, respectively. The output should be the string 'alarm!' if any two of the temperature readings disagree by strictly more than 10 degrees and 'normal' otherwise.

In [135]:
def my_nuke_alarm(s1,s2,s3):
    # write your function code here
    a1 = abs(s1-s2) > 10
    a2 = abs(s1-s3) > 10
    a3 = abs(s2-s3) > 10
    s = a1 + a2 + a3
    if s>1:
        response = 'alarm!'
    else:
        response = 'normal'
    return response

In [136]:
#Output: 'normal'
my_nuke_alarm(94,96,90)

'normal'

In [137]:
#Output: 'alarm!'
my_nuke_alarm(94,96,80)

'alarm!'

In [138]:
#Output: 'normal'
my_nuke_alarm(100,96,90)

'normal'

### 6.
Let Q(x) be the quadratic equation $Q(x) = ax^2 + bx + c$ for some scalar values *a*, *b*, and *c*. A root of $Q(x)$ is an *r* such that $Q(r) = 0$. The two roots of a quadratic equation can be described by the quadratic formula, which is

$$r = \frac{-b\pm\sqrt{b^2-4ac}}{2a}$$

A quadratic equation has either two real roots (i.e., $b^2 > 4ac$), two imaginary roots (i.e., $b^2 < 4ac$), or one root, $r = − \frac{b}{2a}$.

Write a function *my_n_roots(a,b,c)*, where *a*, *b*, and *c* are the coefficients of the quadratic $Q(x)$, the function should return two values: *n_roots* and *r*. *n_roots* is 2 if *Q* has two real roots, 1 if *Q* has one root, −2 if *Q* has two imaginary roots, and *r* is an array containing the roots of *Q*.

In [140]:
def my_n_roots(a,b,c):
    # write your function code here
    if b**2-4*a*c > 0:
        n_roots = 2
        r = [(-b+(b**2-4*a*c)**0.5)/2/a, (-b-(b**2-4*a*c)**0.5)/2/a]
    elif b**2-4*a*c == 0:
        n_roots = 1
        r = [(-b+(b**2-4*a*c)**0.5)/2/a]
    else:
        n_roots = -2
        r = [(-b+(b**2-4*a*c)**0.5)/2/a, (-b-(b**2-4*a*c)**0.5)/2/a]
    return n_roots, r

In [141]:
# Output: n_roots = 2, r = [3, -3]
n_roots, r = my_n_roots(1,0,-9)
print(n_roots, r)

2 [3.0, -3.0]


In [142]:
# Output: n_roots = -2, r = [(-0.6667 + 1.1055j), (-0.6667 - 1.1055j)]
my_n_roots(3,4,5)

(-2,
 [(-0.6666666666666666+1.1055415967851332j),
  (-0.6666666666666666-1.1055415967851332j)])

In [143]:
# Output: n_roots = 1, r = [1]
my_n_roots(2,4,2)

(1, [-1.0])

## Exercise 5: Loops (Iterations)

For this Exercise, you need to commplete all the following problems. Please comment your code when neccessary. Most of these problems were taken straight from  [Python Numerical Methods](https://pythonnumericalmethods.berkeley.edu/notebooks/chapter05.04-Summary-and-Problems.html#problems), but there have been modifications. Please read chapter 5.


#### For all of the problems, please use the cells provided for each problem.

nt### 1. 
What will the value of y be after the following code is executed? Try to figure this out without running code.

```python
y = 0
for i in range(1000):
    for j in range(1000):
        if i == j:
            y += 1
```

**Type your answer to Problem 1 here: 1000**

### 2.
Write a function *my_n_max(x, n)* to return a list consisting of the n largest elements of *x*. You may use Python's *max* function. You may also assume that *x* is a one-dimensional list with no duplicate entries, and that *n* is strictly positive integer smaller than the length of *x* 

In [150]:
x = [7, 9, 10, 5, 8, 3, 4, 6, 2, 1]

def my_n_max(x, n):
    # write your function code here
    x.sort(reverse=True)
    out = x[:n]
    return out

In [151]:
# Output = [10, 9, 8]
n=3
out = my_n_max(x, n)
print(out)

[10, 9, 8]


### 3.
Let *P* be an $m \times p$ array and Q be a $p \times n$ array. As you will find later in this book, $M = P \times Q$ is defined as $M[i, j] = \sum_{k=1}^{p}P[i, k]\cdot Q[k, j]$. Write a function *my_mat_mult(P, Q) that uses for-loops to compute *M*, the matrix product of *P* and *Q*. Hint: You may need up to three nested for-loops. Do **NOT** use the function *np.dot()*.

In [155]:
import numpy as np

def my_mat_mult(P, Q):
    # write your function code here
    M = np.zeros([P.shape[0], Q.shape[1]])
    for i in range(0, M.shape[0]):
        for j in range(0, M.shape[1]):
            M[i,j] = np.sum(P[i,:]*Q[:,j])
    return M

In [156]:
# Output:
#  array([[3., 3., 3.],
#        [3., 3., 3.],
#        [3., 3., 3.]])

P = np.ones((3, 3))
my_mat_mult(P, P)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [157]:
# Output:
# array([[30, 30, 30],
#       [70, 70, 70]])

P = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
Q = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3], [4, 4, 4]])
my_mat_mult(P, Q)

array([[30., 30., 30.],
       [70., 70., 70.]])

### 4. 
The interest, $i$, on a principle, $P_0$, is a payment for allowing the bank to use your money. Compound interest is accumulated according to the formula $P_n = (1 + i)P_{n-1}$, where n is the compounding period, usually in months or years. Write a function *my_saving_plan(P0, i, goal)* where the output is the number of years it will take $P_0$ to become goal at $i\%$ interest compounded annually. 

In [158]:
def my_saving_plan(P0, i, goal):
    # write your function code here
    years = 0
    while(P0<goal):
        P0 = P0 * (1+i)
        years += 1
    return years

In [159]:
# Output: 15
my_saving_plan(1000, 0.05, 2000)

15

In [160]:
# Output: 11
my_saving_plan(1000, 0.07, 2000)

11

In [161]:
# Output: 21
my_saving_plan(500, 0.07, 2000)

21

### 5.
Write a function *my_trig_odd_even(M)*, where the output $Q[i, j] = sin (\pi/M[i, j])$ if $M[i,j]$ is odd, and $Q[i, j] = cos (\pi/M[i, j])$ if $M[i, j]$ is even. Assume that M is a two-dimensional array of strictly positive integers.

In [185]:
def my_trig_odd_even(M):
    # write your function code here
    M = np.array(M)
    Q = np.zeros([M.shape[0], M.shape[1]])
    for i in range(0, M.shape[0]):
        for j in range(0, M.shape[1]):
            if M[i,j] % 2 ==0:
                Q[i,j]=np.cos(np.pi/M[i,j])
            if M[i,j] % 2 ==1:
                Q[i,j]=np.sin(np.pi/M[i,j])
    return Q

In [186]:
# Output: [[0.8660, 0.7071], [0.8660, 0.4339]]
M = [[3, 4], [6, 7]]
my_trig_odd_even(M)

array([[0.8660254 , 0.70710678],
       [0.8660254 , 0.43388374]])

### 6. 
Turn the list *words* of lower case characters to upper case using list comprehension. 

In [188]:
words = ['test', 'data', 'analyze']
new = [x.upper() for x in words]
print(new)

['TEST', 'DATA', 'ANALYZE']
